### ISSUE TITLE
FIrewall Error

### ISSUE THREAD

**Issue by VA3ROM** [provector/wxtoproxy#1]
I have setup WxtoImag Internet optons as per instructions. Run wxtoproxy but when trying to get Keplers using WxtoImg just keep getting Error message that it can't access www.celestrak.com and to check Firewall settings. I've looked and don't see what I have to do. Can you help me?

Thanks,
Robert

**Comment by VA3ROM** [comment]
Found the problem! Had to give wxtoproxy admin privelages and it now runs and opens up a DOS box and WxtoImg can now update the Keps! I thought that WxtoImg was done for.

Many thanks!

Robert

**Comment by provector** [comment]
It seems like it happens on some systems. It's probably possible to add an "auto rule" to the firewall through windows API or something.

**Comment by dbzx6r** [comment]
Running as administrator seems to still give me errors
